import {COLORS, CARD_TYPES, HOME_DIR, RARITY_COLOR} from "./definitions"
import {SINGLETON} from "./greps"
import {pluralize} from "../functions/text"

export const pageButtons = [
	{
		label: "Create",
		icon: require("../imgs/icon-deck-new.svg"),
		link: `deck/new`,
		desc: `Create a new deck from scratch, from a file, or procedurally from a seed card. (Create an account to make stuff!)`,
		auth: true,
	},
	{
		label: "Decks",
		icon: require("../imgs/icon-deck-search.svg"),
		link: `deck/search`,
		desc: `Browse all user-submitted decklists.`,
	},
	{
		label: "Cards",
		icon: require("../imgs/icon-card-search.svg"),
		link: `card/search`,
		desc: `Find any MTG card using a tag-search system. Also add cards to your cart and export without signing in.`,
	},
	{
		label: "Playtest",
		icon: require("../imgs/icon-play.svg"),
		link: `playtest/lobby`,
		desc: `Playtest your favorite lists. PvP coming soon.`,
	},
]

function importAll(r) {
	let images = {}
	r.keys().map(item => {
		images[item.replace("./", "")] = r(item)
	})
	return images
}

export const ItemTypes = {
	CARD: "CARD",
	COMMANDER: "COMMANDER",
}
export const FORMATS = [
	"brawl",
	"commander",
	"duel",
	"future",
	"legacy",
	"modern",
	"oldschool",
	"pauper",
	"penny",
	"standard",
	"vintage",
	"casual",
]

export const illegalLayouts = [
	"token",
	"double_faced_token",
	"scheme",
	"planar",
	"emblem",
	"vanguard",
	"art_series",
]

export const helpTiers = ["No", "From Friends", "Yes", "Wanted"]

export const STACKTIONS = [
	"Action",
	"Spell",
	"Activated Ability",
	"Triggered Ability",
]

export const OPs = (numeric, legality) =>
	numeric
		? ["=", ">", "<", ">=", "<=", "!="]
		: legality
		? ["Legal", "Not Legal", "Restricted", "Banned"]
		: ["AND", "OR", "NOT"]
const numOpt = [
	...[...Array(17)].map((_, i) => "" + i),
	"POWER",
	"TOUGHNESS",
	"CMC",
]

export const advancedFields = [
	{
		name: "Colors",
		trait: "colors",
		colored: true,
		options: COLORS("symbol"),
	},
	{
		name: "Color Identity",
		trait: "color_identity",
		colored: true,
		options: COLORS("symbol"),
	},
	{
		name: "# of Colors",
		trait: "colors",
		numeric: true,
		options: [...Array(6)].map((_, i) => i + ""),
	},
	{
		name: "Name",
		trait: "name",
		ex: 'ex: "Witness"',
	},

	{
		name: "Text",
		trait: "oracle_text",
		ex: 'ex: "When ~ enters"',
	},

	{
		name: "Types",
		trait: "type_line",
		ex: 'ex. "Creature" or "Human"',
	},
	{
		name: "Keywords",
		trait: "keywords",
	},
	{
		name: "# of Keywords",
		trait: "keywords",
		numeric: true,
		options: [...Array(10)].map((_, i) => i + ""),
	},
	{
		name: "Mana Cost",
		trait: "mana_cost",
		ex: 'ex. "1GG"',
	},

	{
		name: "CMC",
		trait: "cmc",
		numeric: true,
		options: numOpt.filter(n => n !== "CMC"),
	},

	{
		name: "Power",
		trait: "power",
		numeric: true,
		options: numOpt.filter(n => n !== "POWER"),
	},
	{
		name: "Toughness",
		trait: "toughness",
		numeric: true,
		options: numOpt.filter(n => n !== "TOUGHNESS"),
	},
	{
		name: "Loyalty",
		trait: "loyalty",
		numeric: true,
		options: numOpt,
	},
	{
		name: "Layout",
		trait: "layout",
		options: [
			"normal",
			"split",
			"flip",
			"transform",
			"modal_dfc",
			"meld",
			"leveler",
			"saga",
			"adventure",
		],
	},
	{
		name: "Flavor Text",
		trait: "flavor_text",
		ex: 'ex. "Remembers ever word"',
	},
	{
		name: "Set",
		trait: "set_name",
	},
	{
		name: "Rarity",
		trait: "rarity",
		options: ["common", "uncommon", "rare", "mythic"],
	},
	// {
	// 	name: "Artist",
	// 	trait: "artist",
	// 	desc:
	// 		"Note: Only the most recent printings of cards are included in search, not every art piece is represented.",
	// 	ex: "ex. John Avon",
	// },
	{
		name: "Price",
		trait: "prices",
		subTrait: "usd",
		numeric: true,
		desc:
			"In US dollars, rounded down. Note: Price-data is only for the most recent printing, and many entries are incomplete.",
		options: [...Array(100)].map((_, i) => i + ""),
	},
	{
		name: "Legalities",
		trait: "legalities",
		legality: true,
		options: FORMATS,
	},
	{
		name: "EDHREC Rank",
		trait: "edhrec_rank",
		numeric: true,
		options: [...Array(50)].map((_, i) => i * 1000 + ""),
	},
]

export const CARD_SLEEVES = importAll(
	require.context("../../public/images/sleeves", false, /\.(png|jpe?g|svg)$/)
)
export const PLAYMATS = importAll(
	require.context("../../public/images/playmats", false, /\.(png|jpe?g|svg)$/)
)

export const CONTROL_CARD = {
	object: "card",
	id: "UNKNOWN_ID",
	name: "Unknown Card",
	lang: "en",
	released_at: "2000-01-01",
	image_uris: {},
	mana_cost: "{1}",
	cmc: -1,
	type_line: "Missing — Type",
	oracle_text: "",
	power: "1",
	toughness: "1",
	colors: [],
	color_identity: [],
	keywords: [],
	legalities: {
		standard: "not_legal",
		future: "not_legal",
		historic: "not_legal",
		pioneer: "not_legal",
		modern: "not_legal",
		legacy: "not_legal",
		pauper: "not_legal",
		vintage: "not_legal",
		penny: "not_legal",
		commander: "not_legal",
		brawl: "not_legal",
		duel: "not_legal",
		oldschool: "not_legal",
	},
	nonfoil: true,
	set: "non",
	set_name: "None",
	rulings_uri: "http://missingurl.com/no_rulings_uri_found",
	rarity: "common",
	flavor_text: "...",
	artist: "Unknown",
	border_color: "black",
	frame: "0000",
	edhrec_rank: -1,
	prices: {
		usd: "0.00",
		usd_foil: "0.00",
		eur: "0.00",
		tix: "0.00",
	},
}

export const NUMBER_WORDS = [
	"zero",
	"one",
	"two",
	"three",
	"four",
	"five",
	"six",
	"seven",
	"eight",
	"nine",
	"ten",
	"eleven",
	"twelve",
	"thirteen",
	"fourteen",
	"fifteen",
	"sixteen",
	"seventeen",
	"eighteen",
	"nineteen",
]
export const SPECIAL_SYMBOLS = [
	"artifact",
	"creature",
	"enchantment",
	"instant",
	"land",
	"planeswalker",
	"sorcery",
	"0",
	"1",
	"2",
	"3",
	"4",
	"5",
	"6",
	"7",
	"8",
	"9",
	"10",
	"11",
	"12",
	"13",
	"14",
	"15",
	"16",
	"17",
	"18",
	"19",
	"20",
	"100",
	"1000000",
	"w",
	"u",
	"b",
	"r",
	"g",
	"x",
	"y",
	"z",
	"p",
	"wp",
	"up",
	"bp",
	"rp",
	"gp",
	"s",
	"c",
	"e",
	"wu",
	"wb",
	"rw",
	"gw",
	"2w",
	"ub",
	"ur",
	"wu",
	"gu",
	"2u",
	"br",
	"bg",
	"wb",
	"ub",
	"2b",
	"rw",
	"rg",
	"ur",
	"br",
	"2r",
	"gw",
	"gu",
	"bg",
	"rg",
	"2g",
	"2w",
	"2u",
	"2b",
	"2r",
	"2g",
	"energy",
	"tap",
	"untap",
	"tap-alt",
	"chaos",
	"1-2",
	"infinity",
	"multiple",
	"loyalty-up",
	"loyalty-down",
	"loyalty-zero",
	"loyalty-start",
	"flashback",
	"dfc-night",
	"dfc-day",
	"dfc-ignite",
	"dfc-spark",
	"dfc-emrakul",
	"dfc-moon",
	"dfc-enchantment",
	"power",
	"toughness",
	"artist-brush",
	"artist-nib",
	"guild-azorius",
	"guild-boros",
	"guild-dimir",
	"guild-golgari",
	"guild-gruul",
	"guild-izzet",
	"guild-orzhov",
	"guild-rakdos",
	"guild-selesnya",
	"guild-simic",
	"clan-abzan",
	"clan-jeskai",
	"clan-mardu",
	"clan-sultai",
	"clan-temur",
	"clan-atarka",
	"clan-dromoka",
	"clan-kolaghan",
	"clan-ojutai",
	"clan-silumgar",
	"polis-setessa",
	"polis-akros",
	"polis-meletis",
]
export const GREETINGS = [
	"Hello",
	"Hey",
	"Hi",
	"Hark",
	"Howdy",
	"Hiya",
	"How's it Goin'",
	"Salutations",
	"What's New",
	"How's Your Day",
	"Welcome Back",
	"Long Time No See",
	"It's About Time",
]

export const SUB_BANNERS = [
	"Making Magic™ happen fast!",
	"After 10,000 Years... It is here",
	"Not what you hoped for, yet more than you ever dreamed",
	"We're all happy campers",
	"Recruiting Everyone",
	"Better Every Day",
]

export const EXAMPLE_DECK_NAMES = [
	"Timmy's BIG Surprise",
	"Roon's War Crimes",
	"Kaput",
	"Septa",
	"Something Clever",
	"Johnny Cash Money",
]

export const EXAMPLE_DECK_DESCS = [
	" I'm a new and impressionable deck that needs guidance and a good description.",
	" Hey there, I'm new in town.",
	" This is my dumb stupid aggro deck. Here's how it works:\n T3: AAAAAAAAAAHHH!",
	" T1 swamp, T2 swamp, T3 swamp, T4 swamp, T5 swamp Sidisi, T6 swamp ad naus dark sphere rit sickening dreams GG",
	" Just gonna leave this here...",
	"This list comes to you shamelessly copied and pasted from a more talented deck builder",
]

const priceThresholds = [
	{val: 2, label: "bulk"},
	{val: 5, label: "$2 +"},
	{val: 15, label: "$5 +"},
	{val: 25, label: "$15 +"},
	{val: 50, label: "$25 +"},
	{val: 100, label: "$50 +"},
	{val: 300, label: "$100 +"},
	{val: 600, label: "$300 +"},
	{val: 1000, label: "BLOOD MONEY"},
]

export const FILTER_TERMS = [
	{
		name: "Type",
		key: "type_line",
		vals: CARD_TYPES,
		valNames: CARD_TYPES.map(T => pluralize(T)),
		icon: true,
	},
	{
		name: "Custom",
		key: "custom",
		other: "uncategorized",
	},
	{
		name: "CMC",
		key: "cmc",
		vals: [...Array(20)].map((a, i) => i),
		valNames: NUMBER_WORDS.map(n => n + " drops"),
	},
	{
		name: "Color",
		key: "colors",
		vals: COLORS("symbol"),
		valNames: COLORS("name"),
		fill: COLORS("fill"),
		other: "multicolor",
		icon: true,
	},
	{
		name: "Price (USD)",
		key: "prices",
		subKey: "usd",
		vals: priceThresholds.map(p => p.val),
		valNames: priceThresholds.map(p => p.label),
		other: "missing USD price",
	},
	{
		name: "Price (TIX)",
		key: "prices",
		subKey: "tix",
		vals: priceThresholds.map(p => p.val),
		valNames: priceThresholds.map(p => p.label),
		other: "missing TIX price",
	},
	{
		name: "Artist",
		key: "artist",
	},
	{
		name: "Set",
		key: "set_name",
	},
	{
		name: "Frame",
		key: "frame",
	},
	{
		name: "Layout",
		key: "layout",
	},
	{
		name: "Rarity",
		key: "rarity",
		vals: ["mythic", "rare", "uncommon", "common"],
		fill: ["mythic", "rare", "uncommon", "common"].map(r => RARITY_COLOR[r]),
	},
]
export const THEN_FILTERS = [
	{
		name: "Name",
		key: "name",
	},
	{
		name: "CMC",
		key: "cmc",
	},
	{
		name: "Type",
		key: "type_line",
	},
	{
		name: "Power",
		key: "power",
	},
	{
		name: "Toughness",
		key: "toughness",
	},
]

export const COUNTERS = [
	"+1/+1",
	" Loyalty",
	" Fade",
	" Deathtouch",
	" Double strike",
	" Flying",
	" Hexproof",
	" Indestrucible",
	" Level",
	" Lifelink",
	" Menace",
	" Poison",
	" Quest",
	" Reach",
	" Time",
	" Trample",
	" Vigilance",
	" Acorn",
	" Age",
	" Aim",
	" Arrow",
	" Arrowhead",
	" Awakening",
	" Blaze",
	" Blood",
	" Bounty",
	" Bribery",
	" Brick",
	" Cage",
	" Carrion",
	" Charge",
	" Coin",
	" CRANK!",
	" Credit",
	" Corpse",
	" Crystal",
	" Cube",
	" Currency",
	" Death",
	" Delay",
	" Depletion",
	" Despair",
	" Devotion",
	" Divinity",
	" Doom",
	" Dream",
	" Echo",
	" Egg",
	" Elixir",
	" Energy",
	" Eon",
	" Experience",
	" Eyeball",
	" Eyestalk",
	" Fate",
	" Feather",
	" Fetch",
	" Filibuster",
	" First strike",
	" Flood",
	" Fungus",
	" Fuse",
	" Gem",
	" Glyph",
	" Gold",
	" Growth",
	" Hatchling",
	" Healing",
	" Hit",
	" Hoofprint",
	" Hour",
	" Hourglass",
	" Hunger",
	" Ice",
	" Incubation",
	" Infection",
	" Intervention",
	" Isolation",
	" Javelin",
	" Ki",
	" Knowledge",
	" Lore",
	" Luck",
	" Magnet",
	" Manabond",
	" Manifestation",
	" Mannequin",
	" Mask",
	" Matrix",
	" Mine",
	" Mining",
	" Mire",
	" Music",
	" Muster",
	" Net",
	" Omen",
	" Ore",
	" Page",
	" Pain",
	" Paralyzation",
	" Petal",
	" Petrification",
	" Phylactery",
	" Pin",
	" Plague",
	" Polyp",
	" Pressure",
	" Prey",
	" Pupa",
	" Rust",
	" Scream",
	" Shell",
	" Shield",
	" Silver",
	" Shred",
	" Sleep",
	" Sleight",
	" Slime",
	" Slumber",
	" Soot",
	" Soul",
	" Spark",
	" Spore",
	" Storage",
	" Strife",
	" Study",
	" Task",
	" Theft",
	" Tide",
	" Tower",
	" Training",
	" Trap",
	" Treasure",
	" Velocity",
	" Verse",
	" Vitality",
	" Volatile",
	" Wage",
	" Winch",
	" Wind",
	" Wish",
]
