import {COLORS,CARD_TYPES,HOME_DIR,RARITY_COLOR} from './definitions'
import {SINGLETON} from './greps'
import {pluralize} from '../functions/text'

function importAll(r) {
  let images = {}
  r.keys().map(item => { images[item.replace('./', '')] = r(item) })
  return images
}


export const ItemTypes = {
	CARD: 'CARD',
	COMMANDER: 'COMMANDER'
}
export const FORMATS = ['brawl','commander','duel','future','legacy','modern','oldschool','pauper','penny','standard','vintage','casual']

export const CARD_SLEEVES = importAll(require.context('../../public/images/sleeves', false, /\.(png|jpe?g|svg)$/))
export const PLAYMATS = importAll(require.context('../../public/images/playmats', false, /\.(png|jpe?g|svg)$/))

export const NUMBER_WORDS = ['zero','one','two','three','four','five','six','seven','eight','nine','ten','eleven','twelve','thirteen','fourteen','fifteen','sixteen','seventeen','eighteen','nineteen']
export const SPECIAL_SYMBOLS = [
'0','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','100','1000000',
'w','u','b','r','g','x','y','z','p','wp','up','bp','rp','gp','s','c','e',
'wu','wb','rw','gw','2w','ub','ur','wu','gu','2u','br','bg','wb','ub','2b','rw','rg','ur','br','2r','gw','gu','bg','rg','2g','2w','2u','2b','2r','2g',
'energy','tap','untap','tap-alt','chaos','1-2','infinity',
'artifact','creature','enchantment','instant','land','planeswalker','sorcery','multiple',
'loyalty-up','loyalty-down','loyalty-zero','loyalty-start','flashback','dfc-night','dfc-day','dfc-ignite','dfc-spark','dfc-emrakul','dfc-moon','dfc-enchantment','power','toughness','artist-brush','artist-nib',
'guild-azorius','guild-boros','guild-dimir','guild-golgari','guild-gruul','guild-izzet','guild-orzhov','guild-rakdos','guild-selesnya','guild-simic',
'clan-abzan','clan-jeskai','clan-mardu','clan-sultai','clan-temur','clan-atarka','clan-dromoka','clan-kolaghan','clan-ojutai','clan-silumgar',
'polis-setessa','polis-akros','polis-meletis',
]

export const EXAMPLE_DECK_NAMES = [
	"Timmy's BIG Surprise",
	"Roon's War Crimes",
	"Kaput",
	"Septa",
	"Something Clever",
	"Lord of Shit Mountain",
	"Johnny Cash Money"
]

export const EXAMPLE_DECK_DESCS = [
	" I'm a new and impressionable deck that needs guidance and a good description.",
	" Hey there, I'm new in town.",
	" This is my dumb stupid aggro deck. Here's how it works:\n T3: AAAAAAAAAAHHH!",
	" T1 swamp, T2 swamp, T3 swamp, T4 swamp, T5 swamp Sidisi, T6 swamp ad naus dark sphere rit sickening dreams GG",
	" Just gonna leave this here...",
	"This list comes to you shamelessly copied and pasted from a more talented deck builder"
]



const priceThresholds = [
	{val:2,   label:'bulk'},
	{val:5,   label:'$'},
	{val:15,  label:'$$'},
	{val:25,  label:'$$$'},
	{val:50, label:'$$$$'},
	{val:100, label:'$$$$$'},
	{val:300, label:'$$$$$$'},
	{val:600, label:'$$$$$$$'},
	{val:1000, label:'TOO MUCH'},
]

export const FILTER_TERMS = [
	{
		name: "Type",
		key: "type_line",
		vals: CARD_TYPES,
		valNames: CARD_TYPES.map(T=>pluralize(T)),
		icon: true,
	},
	{
		name: "Custom",
		key: "customField",
		other: 'unsorted'
	},
	{
		name: "CMC",
		key: "cmc",
		vals: [...Array(20)].map((a,i)=>i),
		valNames: NUMBER_WORDS.map(n=>n+" drop"),
	},
	{
		name: "Color",
		key: "colors",
		vals: COLORS('symbol'),
		valNames: COLORS('name'),
		fill: COLORS('fill'),
		other: 'multicolor',
		icon: true,
	},
	{
		name: "Price (USD)",
		key: "prices",
		subKey: 'usd',
		vals: priceThresholds.map(p=>p.val),
		valNames: priceThresholds.map(p=>p.label),
		other: 'missing USD price',
	},
	{
		name: "Price (TIX)",
		key: "prices",
		subKey: 'tix',
		vals: priceThresholds.map(p=>p.val),
		valNames: priceThresholds.map(p=>p.label),
		other: 'missing TIX price',
	},
	{
		name: "Artist",
		key: "artist",
	},
	{
		name: "Set",
		key: "set_name",
	},
	{
		name: "Frame",
		key: "frame",
	},
	{
		name: "Rarity",
		key: "rarity",
		vals: [
		'mythic',
		'rare',
		'uncommon',
		'common',
		],
		fill: [
		'mythic',
		'rare',
		'uncommon',
		'common',
		].map(r=>RARITY_COLOR[r])
	},
]


export const SUB_TYPES = [
	"Advisor",
	"Aetherborn",
	"Ally",
	"Angel",
	"Antelope",
	"Ape",
	"Archer",
	"Archon",
	"Army",
	"Artificer",
	"Assassin",
	"Assembly-Worker",
	"Atog",
	"Aurochs",
	"Avatar",
	"Azra",
	"Badger",
	"Barbarian",
	"Basilisk",
	"Bat",
	"Bear",
	"Beast",
	"Beeble",
	"Berserker",
	"Bird",
	"Blinkmoth",
	"Boar",
	"Bringer",
	"Brushwagg",
	"Camarid",
	"Camel",
	"Caribou",
	"Carrier",
	"Cat",
	"Centaur",
	"Cephalid",
	"Chimera",
	"Citizen",
	"Cleric",
	"Cockatrice",
	"Construct",
	"Coward",
	"Crab",
	"Crocodile",
	"Cyclops",
	"Dauthi",
	"Demigod",
	"Demon",
	"Deserter",
	"Devil",
	"Dinosaur",
	"Djinn",
	"Dog",
	"Dragon",
	"Drake",
	"Dreadnought",
	"Drone",
	"Druid",
	"Dryad",
	"Dwarf",
	"Efreet",
	"Egg",
	"Elder",
	"Eldrazi",
	"Elemental",
	"Elephant",
	"Elf",
	"Elk",
	"Eye",
	"Faerie",
	"Ferret",
	"Fish",
	"Flagbearer",
	"Fox",
	"Frog",
	"Fungus",
	"Gargoyle",
	"Germ",
	"Giant",
	"Gnome",
	"Goat",
	"Goblin",
	"God",
	"Golem",
	"Gorgon",
	"Graveborn",
	"Gremlin",
	"Griffin",
	"Hag",
	"Harpy",
	"Hellion",
	"Hippo",
	"Hippogriff",
	"Homarid",
	"Homunculus",
	"Horror",
	"Horse",
	"Human",
	"Hydra",
	"Hyena",
	"Illusion",
	"Imp",
	"Incarnation",
	"Insect",
	"Jackal",
	"Jellyfish",
	"Juggernaut",
	"Kavu",
	"Kirin",
	"Kithkin",
	"Knight",
	"Kobold",
	"Kor",
	"Kraken",
	"Lamia",
	"Lammasu",
	"Leech",
	"Leviathan",
	"Lhurgoyf",
	"Licid",
	"Lizard",
	"Manticore",
	"Masticore",
	"Mercenary",
	"Merfolk",
	"Metathran",
	"Minion",
	"Minotaur",
	"Mole",
	"Monger",
	"Mongoose",
	"Monk",
	"Monkey",
	"Moonfolk",
	"Mouse",
	"Mutant",
	"Myr",
	"Mystic",
	"Naga",
	"Nautilus",
	"Nephilim",
	"Nightmare",
	"Nightstalker",
	"Ninja",
	"Noble",
	"Noggle",
	"Nomad",
	"Nymph",
	"Octopus",
	"Ogre",
	"Ooze",
	"Orb",
	"Orc",
	"Orgg",
	"Otter",
	"Ouphe",
	"Ox",
	"Oyster",
	"Pangolin",
	"Peasant",
	"Pegasus",
	"Pentavite",
	"Pest",
	"Phelddagrif",
	"Phoenix",
	"Pilot",
	"Pincher",
	"Pirate",
	"Plant",
	"Praetor",
	"Prism",
	"Processor",
	"Rabbit",
	"Rat",
	"Rebel",
	"Reflection",
	"Rhino",
	"Rigger",
	"Rogue",
	"Sable",
	"Salamander",
	"Samurai",
	"Sand",
	"Saproling",
	"Satyr",
	"Scarecrow",
	"Scion",
	"Scorpion",
	"Scout",
	"Sculpture",
	"Serf",
	"Serpent",
	"Servo",
	"Shade",
	"Shaman",
	"Shapeshifter",
	"Shark",
	"Sheep",
	"Siren",
	"Skeleton",
	"Slith",
	"Sliver",
	"Slug",
	"Snake",
	"Soldier",
	"Soltari",
	"Spawn",
	"Specter",
	"Spellshaper",
	"Sphinx",
	"Spider",
	"Spike",
	"Spirit",
	"Splinter",
	"Sponge",
	"Squid",
	"Squirrel",
	"Starfish",
	"Surrakar",
	"Survivor",
	"Tentacle",
	"Tetravite",
	"Thalakos",
	"Thopter",
	"Thrull",
	"Treefolk",
	"Trilobite",
	"Triskelavite",
	"Troll",
	"Turtle",
	"Unicorn",
	"Vampire",
	"Vedalken",
	"Viashino",
	"Volver",
	"Wall",
	"Warlock",
	"Warrior",
	"Weird",
	"Werewolf",
	"Whale",
	"Wizard",
	"Wolf",
	"Wolverine",
	"Wombat",
	"Worm",
	"Wraith",
	"Wurm",
	"Yeti",
	"Zombie",
	"Zubera",
 ]

export const COUNTERS = [
	"PlusOne",
	" Loyalty",
	" Fade",
	" Deathtouch",
	" Double strike",
	" Flying",
	" Hexproof",
	" Indestrucible",
	" Level",
	" Lifelink",
	" Menace",
	" Poison",
	" Quest",
	" Reach",
	" Time",
	" Trample",
	" Vigilance",
	" Acorn",
	" Age",
	" Aim",
	" Arrow",
	" Arrowhead",
	" Awakening",
	" Blaze",
	" Blood",
	" Bounty",
	" Bribery",
	" Brick",
	" Cage",
	" Carrion",
	" Charge",
	" Coin",
	" CRANK!",
	" Credit",
	" Corpse",
	" Crystal",
	" Cube",
	" Currency",
	" Death",
	" Delay",
	" Depletion",
	" Despair",
	" Devotion",
	" Divinity",
	" Doom",
	" Dream",
	" Echo",
	" Egg",
	" Elixir",
	" Energy",
	" Eon",
	" Experience",
	" Eyeball",
	" Eyestalk",
	" Fate",
	" Feather",
	" Fetch",
	" Filibuster",
	" First strike",
	" Flood",
	" Fungus",
	" Fuse",
	" Gem",
	" Glyph",
	" Gold",
	" Growth",
	" Hatchling",
	" Healing",
	" Hit",
	" Hoofprint",
	" Hour",
	" Hourglass",
	" Hunger",
	" Ice",
	" Incubation",
	" Infection",
	" Intervention",
	" Isolation",
	" Javelin",
	" Ki",
	" Knowledge",
	" Lore",
	" Luck",
	" Magnet",
	" Manabond",
	" Manifestation",
	" Mannequin",
	" Mask",
	" Matrix",
	" Mine",
	" Mining",
	" Mire",
	" Music",
	" Muster",
	" Net",
	" Omen",
	" Ore",
	" Page",
	" Pain",
	" Paralyzation",
	" Petal",
	" Petrification",
	" Phylactery",
	" Pin",
	" Plague",
	" Polyp",
	" Pressure",
	" Prey",
	" Pupa",
	" Rust",
	" Scream",
	" Shell",
	" Shield",
	" Silver",
	" Shred",
	" Sleep",
	" Sleight",
	" Slime",
	" Slumber",
	" Soot",
	" Soul",
	" Spark",
	" Spore",
	" Storage",
	" Strife",
	" Study",
	" Task",
	" Theft",
	" Tide",
	" Tower",
	" Training",
	" Trap",
	" Treasure",
	" Velocity",
	" Verse",
	" Vitality",
	" Volatile",
	" Wage",
	" Winch",
	" Wind", 
	" Wish",
]